
# The list of source files for the src. Export the names to the Kbuild file.
SRC_DIR = src
export SRC_FILES = imx6q_amp_sgi.c 
SRC_PATHS = $(addprefix $(SRC_DIR)/,$(SRC_FILES))

KERNEL_SYMS = $(KERNEL_DIR)/Module.symvers

# The kernel object files generated by compilation
export SW_MODULE_NAME = amp_sgi
SRC_OBJECT = $(SRC_DIR)/$(SW_MODULE_NAME).ko
SRC_OUTPUT_OBJECT = $(OUTPUT_DIR)/$(SW_MODULE_NAME).ko

# Export the include directories to the Kbuild file, making sure the path is
# absolute, as the kernel Makefile is run in a different directory.

#export SRC_INC_DIRS = $(PWD)/$(LIB_INC_DIRS)

################################################################################
# Targets
################################################################################

.PHONY: src

src:$(SRC_OUTPUT_OBJECT)

# Compile the ko against the given kernel. The check targets are phony, so
# don't force this target to run because of them.
$(SRC_OBJECT): $(SRC_PATHS)
	make -C $(KERNEL_DIR) M=$(PWD)/$(SRC_DIR) modules
# Move the compiled ko to the specified output directory
$(SRC_OUTPUT_OBJECT): $(SRC_OBJECT) $(OUTPUT_DIR)
	@mv $< $@
	@mv $(SRC_DIR)/*.o $(OBJ_DIR)
	@mv $(SRC_DIR)/*.symvers $(OBJ_DIR)
	@mv $(SRC_DIR)/*.order $(OBJ_DIR)
	@mv $(SRC_DIR)/*.mod.c $(OBJ_DIR)
	@mv -f $(SRC_DIR)/.[^.]* $(OBJ_DIR)
	
	
